Repository bosagora/agora, pull requests merged in 2019-11, with the labels that each got.

#410 Move the TaskManager instantiation into Node
  source/agora/network/NetworkManager.d
  source/agora/node/Node.d
  source/agora/test/Base.d
Labels: type-refactoring

#420 Make the Schnorr signing routines public
  source/agora/common/crypto/Schnorr.d
Labels: type-enhancement

#421 Add sorting capability to a curve Point
  source/agora/common/crypto/ECC.d
Labels: type-enhancement

#431 Add missing prototypes in the LocalNode wrapper
  source/scpd/scp/LocalNode.d
Labels: type-enhancement

#417 Add the validators and signature to the BlockHeader
  source/agora/consensus/data/Block.d
  tests/system/dub.json
Labels: type-feature

#434 Remove hashing requirement to have `computeHash` implemented
  source/agora/common/Amount.d
  source/agora/common/Hash.d
  source/agora/common/crypto/Key.d
  source/agora/common/crypto/Schnorr.d
  source/agora/consensus/data/Transaction.d
Labels: type-enhancement

#438 Add missing attributes to 'hashPart' overloads
  source/agora/common/Hash.d
Labels: type-bug

#437 Remove requirement for aggregates to implement [de]serialize
  source/agora/common/BanManager.d
  source/agora/common/Deserializer.d
  source/agora/common/Serializer.d
  source/agora/node/API.d
Labels: type-enhancement
