Repository bosagora/agora, pull requests merged in 2019-07, with the labels that each got.

#55 Add basic transaction data layout
  source/agora/common/Data.d
  source/agora/common/Transaction.d
Labels: type-feature

#56 Add initial Block design
  source/agora/common/Block.d
Labels: type-feature

#61 Cache homebrew downloads
  .travis.yml
Labels: type-enhancement

#14 Implement basic metadata caching
  doc/config.example.yaml
  source/agora/common/Config.d
  source/agora/common/Metadata.d
  source/agora/node/Network.d
  source/agora/node/Node.d
  source/agora/node/RemoteNode.d
  source/agora/test/Base.d
  source/agora/test/Metadata.d
Labels: type-feature

#75 Add hashing support to BlockHeader
  source/agora/common/Block.d
Labels: type-enhancement

#77 Ledger: Get rid of double-lookup in addNewBlock
  source/agora/node/Ledger.d
Labels: type-enhancement

#79 Implement the getBlockHeight() API method
  source/agora/common/API.d
  source/agora/node/Node.d
  source/agora/test/GossipProtocol.d
Labels: type-feature

#76 Implement the getBlocksFrom() method
  source/agora/common/API.d
  source/agora/node/Ledger.d
  source/agora/node/Node.d
  source/agora/test/Ledger.d
Labels: type-feature

#82 Simplify creation of metadata in the unittests
  source/agora/node/Node.d
  source/agora/test/Base.d
Labels: type-enhancement

#84 Correct documentation and error message in Hash module
  source/agora/common/Hash.d
Labels: type-enhancement

#87 Move transaction verification into the Ledger
  source/agora/node/GossipProtocol.d
  source/agora/node/Ledger.d
Labels: type-enhancement

#91 style-guide: Mention using snake_case for variables
  doc/Style.md
Labels: type-enhancement

#90 Simplify and speed up transaction verification
  source/agora/common/Transaction.d
  source/agora/node/Ledger.d
Labels: type-enhancement

#95 Improve docs in RemoteNode and rename some delegates
  source/agora/node/RemoteNode.d
Labels: type-refactoring

#98 Add a commit style guide
  doc/Style.md
Labels: type-enhancement

#107 Fix some serialization function and Add Annotation
  source/agora/node/BlockSerialize.d
Labels: type-enhancement

#108 Add some BanManager improvements
  source/agora/common/BanManager.d
Labels: type-enhancement, type-refactoring

#111 Fix check in the Ledger unittest
  source/agora/test/Ledger.d
Labels: type-bug

#112 Implemented API for Merkle proof
  source/agora/common/API.d
  source/agora/common/Block.d
  source/agora/node/Ledger.d
  source/agora/node/Node.d
  source/agora/test/Ledger.d
Labels: type-feature
