Repository bosagora/agora, pull requests merged in 2019-08, with the labels that each got.

#134 Travis: Build & run the tests before building the app
  .travis.yml
Labels: type-refactoring

#129 Apply `binary search algorithm` to Block.findHashIndex
  source/agora/common/Block.d
Labels: type-enhancement

#130 [trivial] Reorder imports according to our style guide
  source/agora/network/NetworkClient.d
  source/agora/network/NetworkManager.d
  source/agora/test/Base.d
  source/agora/test/GossipProtocol.d
  source/agora/test/Ledger.d
  source/agora/test/NetworkClient.d
  source/scpd/scp/BallotProtocol.d
  source/scpd/scp/NominationProtocol.d
  source/scpd/scp/SCP.d
  source/scpd/scp/SCPDriver.d
  source/scpd/scp/Slot.d
  source/scpd/tests/GlueTypes.d
  source/scpd/types/Stellar_SCP.d
  source/scpd/types/Stellar_types.d
  source/scpd/types/XDRBase.d
Labels: type-refactoring

#139 Make deserialization generic
  source/agora/common/Deserializer.d
Labels: type-enhancement

#136 Make node shutdown explicit
  source/agora/app.d
  source/agora/node/Node.d
  source/agora/test/Base.d
  source/agora/test/GossipProtocol.d
  source/agora/test/Ledger.d
  source/agora/test/Metadata.d
  source/agora/test/Network.d
  source/agora/test/NetworkClient.d
Labels: type-enhancement

#146 Enhance / refactor some test-suite code
  source/agora/test/Base.d
  source/agora/test/Ledger.d
  source/agora/test/NetworkClient.d
Labels: type-enhancement

#152 Test with Xenial only on Linux
  .travis.yml
Labels: type-deprecation

#131 Upgrade to use multiple memory map files
  source/agora/common/BlockStorage.d
Labels: type-feature

#163 Reduce the number of txs created in a test
  source/agora/test/Ledger.d
Labels: type-bug, type-refactoring

#161 Update the style guide to mention attributes
  doc/Style.md
Labels: type-enhancement

#168 Change memory map size & fix up styling
  source/agora/common/BlockStorage.d
Labels: type-enhancement, type-refactoring

#175 Get rid of templated Network parameter
  source/agora/node/Node.d
  source/agora/node/main.d
  source/agora/test/Base.d
Labels: type-refactoring

#178 Get rid of the MetaTestNetwork
  source/agora/test/Base.d
  source/agora/test/Metadata.d
Labels: type-refactoring

#188 Make an overload of buildMerkleTree() which has no side-effects
  source/agora/consensus/data/Block.d
Labels: type-refactoring

#189 Remove @nogc attribute from validation function
  source/agora/consensus/data/Block.d
Labels: type-refactoring

#185 Rename mergeHash() to hashMulti() and make it generic
  source/agora/common/Hash.d
  source/agora/consensus/data/Block.d
  source/agora/node/Ledger.d
  source/agora/test/Ledger.d
Labels: type-enhancement, type-refactoring

#211 Add a Dockerfile to build on Alpine Linux
  .travis.yml
  Dockerfile
Labels: type-feature

#223 Extract `IBlockStorage` from #162
  source/agora/common/BlockStorage.d
Labels: type-enhancement

#162 Integrate BlockStorage with Ledger
  source/agora/network/NetworkManager.d
  source/agora/node/Ledger.d
  source/agora/node/Node.d
Labels: type-feature

#228 Disable system integration test
  .travis.yml
Labels: type-bug

#254 BlockStorage: Add missing handling of return status codes
  source/agora/node/BlockStorage.d
Labels: type-bug, type-enhancement

#217 Don't send a transaction if a node already has it
  source/agora/network/NetworkClient.d
Labels: type-enhancement

#218 Use a checksum in BlockStorage for data integrity validation
  source/agora/node/BlockStorage.d
  tests/unit/BlockStorageChecksum.d
Labels: type-feature

#275 Add the genesis block from within the Ledger
  source/agora/node/BlockStorage.d
  source/agora/node/Ledger.d
Labels: type-enhancement, type-refactoring

#272 Cache the latest block
  source/agora/node/Ledger.d
Labels: type-enhancement

#273 Limit CRC32 checksum data length to 1MB
  source/agora/node/BlockStorage.d
Labels: type-enhancement

#274 Introduce opApply() and remove() for the TransactionPool
  source/agora/common/TransactionPool.d
  source/agora/node/Ledger.d
Labels: type-enhancement, type-refactoring

#278 Make sure tests wait for handshake to complete
  source/agora/test/BanManager.d
  source/agora/test/Ledger.d
Labels: type-bug
