Repository bosagora/agora, pull requests merged in 2019-09, with the labels that each got.

#216 Simplify the findHashIndex() function
  source/agora/consensus/data/Block.d
Labels: type-enhancement, type-refactoring

#219 Replace Json with binary serialization and add an integration test
  source/agora/common/Metadata.d
  tests/unit/Metadata.d
Labels: type-enhancement, type-refactoring

#299 Build SCPP with debugging symbols
  source/scpp/build.d
Labels: type-enhancement

#83 Add a proof of concept for Schnorr signatures
  .travis.yml
  ci/travis_linux_setup.sh
  source/agora/common/crypto/ECC.d
  source/agora/common/crypto/Schnorr.d
Labels: type-feature

#307 Trivial: Minor improvements to the CLI usage / arguments
  source/agora/cli/SendTxProcess.d
Labels: type-enhancement

#324 Fix transaction type a bug that was not saved
  source/agora/consensus/data/Transaction.d
Labels: type-bug

#325 Fix some of the SCP binding code
  source/scpd/scp/SCP.d
  source/scpd/scp/SCPDriver.d
Labels: type-bug

#296 Correctly parse the Quorum config section
  doc/config.example.yaml
  source/agora/common/Config.d
  tests/system/node/0/config.yaml
  tests/system/node/1/config.yaml
  tests/system/node/2/config.yaml
Labels: type-bug, type-enhancement

#320 Fix #270: Add ability to override any config field from the command line
  source/agora/common/Config.d
Labels: type-enhancement

#332 Update bindings to BallotProtocol
  source/scpd/scp/BallotProtocol.d
Labels: type-enhancement

#331 Allow DeserializeDg to throw
  source/agora/common/Amount.d
  source/agora/common/Deserializer.d
  source/agora/common/Set.d
  source/agora/common/crypto/Key.d
  source/agora/consensus/data/Block.d
  source/agora/consensus/data/Transaction.d
  source/agora/node/BlockStorage.d
  source/agora/node/Ledger.d
Labels: type-enhancement

#329 Rename 'deserialize' to 'deserializeFull'
  source/agora/common/Deserializer.d
  source/agora/common/Metadata.d
  source/agora/common/Set.d
  source/agora/common/TransactionPool.d
  source/agora/consensus/data/Transaction.d
  source/agora/consensus/data/UTXOSet.d
  source/agora/node/BlockStorage.d
  source/agora/test/Ledger.d
Labels: type-enhancement

#334 Fix std::vector length() method
  source/scpd/Cpp.d
Labels: type-bug

#339 Emit reason for failed block transaction validation
  source/agora/consensus/Validation.d
Labels: type-enhancement

#335 Add slicing support to the vector binding
  source/scpd/Cpp.d
Labels: type-enhancement

#341 Integration tests: Structure and split the nodes address
  tests/system/source/main.d
Labels: type-enhancement

#338 Change genesis amount to 500,000,000 BOA
  source/agora/consensus/Genesis.d
  source/agora/utils/PrettyPrinter.d
Labels: type-bug

#343 Rename agora.common.Data to agora.common.Types
  source/agora/cli/SendTxProcess.d
  source/agora/common/BanManager.d
  source/agora/common/Deserializer.d
  source/agora/common/Hash.d
  source/agora/common/Metadata.d
  source/agora/common/Serializer.d
  source/agora/common/Set.d
  source/agora/common/TransactionPool.d
  source/agora/common/Types.d
  source/agora/common/crypto/Key.d
  source/agora/common/crypto/Schnorr.d
  source/agora/consensus/Genesis.d
  source/agora/consensus/data/Block.d
  source/agora/consensus/data/Transaction.d
  source/agora/network/NetworkClient.d
  source/agora/network/NetworkManager.d
  source/agora/node/API.d
  source/agora/node/BlockStorage.d
  source/agora/node/GossipProtocol.d
  source/agora/node/Ledger.d
  source/agora/node/Node.d
  source/agora/test/BanManager.d
  source/agora/test/Base.d
  source/agora/test/GossipProtocol.d
  source/agora/test/Ledger.d
  source/agora/test/Metadata.d
  source/agora/test/NetworkClient.d
  source/agora/utils/PrettyPrinter.d
  tests/system/dub.json
  tests/system/source/main.d
  tests/unit/BlockStorage.d
  tests/unit/BlockStorageMultiTx.d
Labels: type-refactoring

#344 Auto-implement interface methods for unittested class
  source/agora/cli/SendTxProcess.d
Labels: type-enhancement

#333 Implement support for walking through an std::set
  source/scpd/Cpp.d
  source/scpd/scp/SCPDriver.d
  source/scpp/extra/DUtils.cpp
Labels: type-enhancement

#337 Implement UTXOSetValue for freezing
  source/agora/consensus/Validation.d
  source/agora/consensus/data/UTXOSet.d
  source/agora/node/Ledger.d
  source/agora/test/Ledger.d
Labels: type-feature

#349 Improve Dockerfile to ignore more things
  .dockerignore
Labels: type-enhancement

#350 Simplify makeTestNetwork()
  source/agora/test/Base.d
Labels: type-enhancement

#352 Make getBlocksFrom() in Ledger return a range
  source/agora/node/Ledger.d
  source/agora/node/Node.d
Labels: type-enhancement

#355 Add missing extern (C++)
  source/scpd/scp/Utils.d
Labels: type-bug

#358 Replace readSizeType() method and read the index file directly
  source/agora/node/BlockStorage.d
Labels: type-refactoring

#359 Simplify the Transaction validation code
  source/agora/common/Amount.d
  source/agora/consensus/Validation.d
Labels: type-refactoring

#361 Change Amount(400_000_000_000L) to Amount.FreezeAmount
  source/agora/consensus/Validation.d
  source/agora/node/Ledger.d
Labels: type-refactoring

#354 Implement variable length integers for Serializer and Deserializer.
  source/agora/common/Deserializer.d
  source/agora/common/Serializer.d
  source/agora/common/Types.d
  source/agora/node/BlockStorage.d
Labels: type-enhancement

#356 Implement double-spending checking and write unit test code
  source/agora/common/TransactionPool.d
  source/agora/node/Ledger.d
Labels: type-enhancement
