Repository bosagora/agora, pull requests merged in 2020-08, with the labels that each got.

#1060 Fix memory leak in restoreSCPState() and fix O(n) loading
  source/agora/consensus/protocol/Nominator.d
Labels: type-bug, type-enhancement

#1093 Re-enable all tests
  source/agora/test/Base.d
  source/agora/test/QuorumPreimage.d
Labels: prio-URGENT, type-bug, type-testing

#1095 prettify: Ocean does not support `scope` in toString()
  source/agora/utils/PrettyPrinter.d
Labels: type-enhancement

#1099 Use enrollments with the same validator cycle as config.yaml
  source/agora/consensus/data/genesis/Test.d
  tests/system/node/0/config.yaml
  tests/system/node/2/config.yaml
  tests/system/node/3/config.yaml
  tests/system/node/4/config.yaml
  tests/system/node/5/config.yaml
  tests/system/node/6/config.yaml
  tests/system/node/7/config.yaml
Labels: type-bug

#1097 Introduce expectBlock() for testing heights
  source/agora/test/BanManager.d
  source/agora/test/Base.d
  source/agora/test/EnrollmentManager.d
  source/agora/test/GenesisBlock.d
  source/agora/test/GossipProtocol.d
  source/agora/test/Ledger.d
  source/agora/test/ManyValidators.d
  source/agora/test/NetworkClient.d
  source/agora/test/NetworkManager.d
  source/agora/test/Quorum.d
  source/agora/test/QuorumPreimage.d
  source/agora/test/Restart.d
  source/agora/test/Simple.d
  source/agora/test/ValidatorCount.d
Labels: type-refactoring

#1103 Fix one more usage of toVec()
  source/agora/consensus/protocol/Nominator.d
Labels: type-bug

#1114 Fix #825 - building agora based on agora-builder image as opposed to alpine image
  Dockerfile
Labels: C.General, Story-Points:2, type-enhancement

#1126 Don't use a static variable for a status flag
  source/agora/network/NetworkManager.d
Labels: type-bug

#1141 [trivial] Properly set dchatty=1 when running tests
  ci/run.sh
Labels: type-testing

#1140 Simplify the implementation of quorum regeneration
  source/agora/node/FullNode.d
  source/agora/node/Ledger.d
  source/agora/node/Validator.d
Labels: type-refactoring

#1144 Disable ManyValidators test as it frequently fails
  source/agora/test/ManyValidators.d
Labels: type-testing
