Repository bosagora/agora, pull requests merged in 2020-01, with the labels that each got.

#466 Mark the Schnorr crypto routines @safe
  source/agora/common/crypto/ECC.d
  source/agora/common/crypto/Schnorr.d
Labels: type-enhancement

#460 Add the enrolled block_height column in the validatorSet DB.
  source/agora/common/EnrollmentManager.d
Labels: type-feature

#465 add isInvalidEnrollmentReason Function in Validation
  source/agora/common/EnrollmentManager.d
  source/agora/consensus/Validation.d
Labels: type-feature

#469 Move UTXOFinder delegate into UTXOSet
  source/agora/consensus/Validation.d
  source/agora/consensus/data/UTXOSet.d
Labels: type-refactoring

#489 [CI] Test compiler HEAD versions on branch push only
  .github/workflows/github_pr.yml
  .github/workflows/github_push.yaml
Labels: status-blocked

#498 Temporarily disable parallel GC
  source/agora/node/main.d
Labels: type-bug

#496 Remove extra dependencies from EnrollmentManager
  source/agora/consensus/EnrollmentManager.d
  source/agora/node/GossipProtocol.d
  source/agora/node/Node.d
  source/agora/test/Base.d
Labels: type-refactoring

#494 Add getUnregisteredEnrollments function in EnrollmentManager
  source/agora/consensus/EnrollmentManager.d
Labels: type-feature

#512 Split validator and full node APIs
  dub.json
  source/agora/api/FullNode.d
  source/agora/api/Validator.d
  source/agora/cli/SendTxProcess.d
  source/agora/cli/main.d
  source/agora/network/NetworkClient.d
  source/agora/network/NetworkManager.d
  source/agora/node/Ledger.d
  source/agora/node/Node.d
  source/agora/test/Base.d
  source/agora/test/NetworkManager.d
  tests/system/dub.json
  tests/system/source/main.d
Labels: type-enhancement
