Repository bosagora/agora, pull requests merged in 2020-11, with the labels that each got.

#1308 Remove unused 'coinbase' functions
  source/agora/consensus/data/Transaction.d
  source/agora/consensus/validation/Transaction.d
Labels: type-refactoring

#1341 Implement time-lock opcodes in the execution engine
  source/agora/script/Engine.d
  source/agora/script/Opcodes.d
Labels: type-feature

#1392 Add better logs for clock time collection
  source/agora/network/NetworkManager.d
Labels: type-enhancement
