Repository bosagora/agora, pull requests merged in 2020-03, with the labels that each got.

#616 Defines the data used when reaching consensus
  source/agora/consensus/data/ConsensusData.d
Labels: type-feature

#623 Sets the address of the node to the argument in system integration test
  ci/system_integration_test.d
  tests/system/source/main.d
Labels: type-enhancement

#626 Nominator: Log out the transaction set which fails validation
  source/agora/consensus/protocol/Nominator.d
Labels: type-enhancement

#628 Fix undefined identifier error on v0.x.x
  source/agora/consensus/protocol/Nominator.d
Labels: prio-URGENT

#627 Use SCPStatementType type directly in _pledges_t
  source/scpd/types/Stellar_SCP.d
Labels: type-enhancement

#504 Write Enrollments data to the block.
  source/agora/consensus/Validation.d
  source/agora/consensus/data/Block.d
  source/agora/node/Ledger.d
  tests/unit/BlockStorage.d
  tests/unit/BlockStorageChecksum.d
  tests/unit/BlockStorageMultiTx.d
Labels: type-feature

#631 Small code improvements
  source/agora/network/NetworkManager.d
  source/agora/test/Base.d
Labels: type-refactoring

#629 Don't accept outdated SCP messages
  source/agora/consensus/protocol/Nominator.d
Labels: type-enhancement

#633 Remove duplicate formatting struct
  source/agora/utils/PrettyPrinter.d
Labels: type-refactoring

#649 tests: Add missing network.waitForDiscovery() call
  source/agora/test/Ledger.d
Labels: prio-URGENT

#655 Update SCPP from 324c1bd6 to v11.2.0
  source/scpp/README.md
  source/scpp/src/main/ErrorMessages.h
  source/scpp/src/scp/LocalNode.cpp
  source/scpp/src/scp/LocalNode.h
  source/scpp/src/scp/QuorumSetUtils.cpp
  source/scpp/src/scp/SCP.cpp
  source/scpp/src/util/Decoder.h
  source/scpp/src/util/Math.cpp
Labels: type-enhancement

#656 Remove leftover task in Node.d
  source/agora/node/Node.d
Labels: type-refactoring

#659 Add missing definition of operator() for hashing support
  dub.json
  source/scpd/scp/SCP.d
  source/scpp/src/crypto/ByteSliceHasher.cpp
  source/scpp/src/crypto/ByteSliceHasher.h
  source/scpp/src/crypto/SecretKey.cpp
  source/scpp/src/util/HashOfHash.cpp
  source/scpp/src/util/HashOfHash.h
Labels: type-bug

#693 Fix syntax error in documentation actions
  .github/workflows/main.yml
Labels: prio-URGENT, type-bug

#696 Fix 695: Install ldc-runtime in the host Docker
  Dockerfile
Labels: type-bug

#662 Add rudimentary bindings to std::unordered_map
  source/scpd/Cpp.d
  source/scpp/extra/DUtils.cpp
  source/scpp/extra/DUtils.h
Labels: type-feature
