Repository bosagora/agora, pull requests merged in 2020-02, with the labels that each got.

#523 Fix #501: Remove test UTXOSet duplication
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/Validation.d
  source/agora/consensus/data/UTXOSet.d
Labels: Story-Points:1, type-enhancement

#525 Fix a potential timing issue with timers in setupTimer()
  source/agora/consensus/protocol/Nominator.d
Labels: type-bug

#480 Add logic to validate enrollments of blockheader
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/Validation.d
Labels: type-feature

#529 SCP build script: Handle file addition / removal on working directory
  source/scpp/build.d
Labels: type-bug

#538 Amount: Add ability to compare amounts
  source/agora/common/Amount.d
Labels: type-enhancement

#549 Make isQuorumSetSane() more informative
  source/scpd/scp/QuorumSetUtils.d
  source/scpp/src/scp/BallotProtocol.cpp
  source/scpp/src/scp/QuorumSetUtils.cpp
  source/scpp/src/scp/QuorumSetUtils.h
Labels: type-enhancement

#554 Revert "Simplify build process slightly"
  README.md
  dub.settings.json
Labels: type-bug

#555 [trivial] Fix counting tests in parallel loop
  source/agora/test/Base.d
Labels: type-bug

#558 Rename 'getUnregisteredEnrollments' to 'getUnregistered'
  source/agora/consensus/EnrollmentManager.d
Labels: type-refactoring

#562 Rename methods in EnrollmentManager
  source/agora/consensus/EnrollmentManager.d
  source/agora/node/GossipProtocol.d
Labels: type-refactoring

#574 Fold GossipProtocol into the Node class
  source/agora/node/GossipProtocol.d
  source/agora/node/Node.d
Labels: type-refactoring

#593 Correctly print compiler's version on push
  .github/workflows/github_push.yaml
Labels: type-bug

#601 Fix #600: Remove dependency on ocean.core.BitArray
  source/agora/common/BitField.d
  source/agora/consensus/data/Block.d
Labels: type-enhancement

#602 Make QuorumConfig fields non-immutable
  source/agora/common/Config.d
  source/agora/node/Node.d
Labels: type-refactoring

#603 Support deserialization of `const` and `immutable` types
  source/agora/common/Deserializer.d
  source/agora/consensus/Genesis.d
  source/agora/node/BlockStorage.d
Labels: type-enhancement
