Repository bosagora/agora, pull requests merged in 2020-04, with the labels that each got.

#714 Emit only error logs when tests fail
  source/agora/test/Base.d
Labels: type-enhancement

#546 Add support for hashing SCPStatement & SCPEnvelope
  source/agora/consensus/protocol/Nominator.d
Labels: type-enhancement

#643 Validator: Connect to all quorum set validators
  source/agora/network/NetworkManager.d
  source/agora/node/Node.d
  source/agora/test/Base.d
  source/agora/test/NetworkDiscovery.d
Labels: type-enhancement

#727 Add automerge workflow
  .github/workflows/automerge.yml
Labels: automerge, type-enhancement

#740 Add @safe to quorum conversion functions
  source/agora/common/Config.d
Labels: automerge, type-refactoring

#743 Fix default compiler setting
  dub.settings.json
Labels: automerge, type-bug

#730 Remove unused MAC routines
  source/scpp/src/crypto/SHA.cpp
  source/scpp/src/crypto/SHA.h
Labels: type-refactoring

#737 Port SCP's hashes into 64-bytes
  source/agora/common/Config.d
  source/agora/consensus/protocol/Nominator.d
  source/agora/utils/SCPPrettyPrinter.d
  source/scpd/scp/LocalNode.d
  source/scpd/tests/LayoutTest.d
  source/scpd/types/Stellar_SCP.d
  source/scpd/types/Stellar_types.d
  source/scpd/types/Utils.d
  source/scpp/extra/DLayoutChecks.cpp
  source/scpp/src/crypto/SHA.cpp
  source/scpp/src/crypto/SHA.h
  source/scpp/src/scp/LocalNode.cpp
  source/scpp/src/scp/SCPDriver.cpp
  source/scpp/src/util/HashOfHash.cpp
  source/scpp/src/util/HashOfHash.h
  source/scpp/src/xdr/Stellar-types.h
Labels: type-enhancement

#749 Fix up namespace linking issue
  source/scpd/Cpp.d
Labels: type-bug

#731 Correct the Github actions CI Test to return the error level correctly
  ci/run.bat
Labels: type-bug

#760 Change derivation method for preimage generation
  source/agora/consensus/EnrollmentManager.d
Labels: type-enhancement

#750 Change the name from NetworkInfo to NodeInfo
  source/agora/api/FullNode.d
  source/agora/network/NetworkClient.d
  source/agora/network/NetworkManager.d
  source/agora/node/Node.d
  source/agora/test/Base.d
  source/agora/test/NetworkDiscovery.d
  tests/system/source/main.d
Labels: type-enhancement

#761 Add PreImageCache to handle sparsely populate preimage range
  source/agora/common/Hash.d
Labels: type-enhancement

#763 Rename `PreimageInfo` to `PreImageInfo`
  source/agora/api/FullNode.d
  source/agora/api/Validator.d
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/Validation.d
  source/agora/consensus/ValidatorSet.d
  source/agora/consensus/data/PreImageInfo.d
  source/agora/network/NetworkClient.d
  source/agora/network/NetworkManager.d
  source/agora/node/Node.d
  source/agora/test/Base.d
  source/agora/test/EnrollmentManager.d
Labels: type-refactoring

#765 Change PreImageInfo.height to distance
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/Validation.d
  source/agora/consensus/ValidatorSet.d
  source/agora/consensus/data/PreImageInfo.d
Labels: type-enhancement

#786 Remove no-longer-necessary cast for deserializeFull argument
  source/agora/consensus/protocol/Nominator.d
Labels: type-refactoring
