Repository bosagora/agora, pull requests merged in 2020-06, with the labels that each got.

#905 Move PreImage utilities into a common module
  source/agora/common/Hash.d
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/PreImage.d
  source/agora/consensus/ValidatorSet.d
Labels: type-refactoring

#908 Annotate makeChainedTransactions as safe
  source/agora/test/NetworkManager.d
  source/agora/utils/Test.d
Labels: type-refactoring

#910 Replace unnecessary scope(success)
  source/agora/node/Validator.d
Labels: type-refactoring

#912 Improve Enrollment validation messages and tests
  source/agora/consensus/validation/Enrollment.d
Labels: type-refactoring

#911 Add an overload of 'sign' which accepts a signature noise
  source/agora/common/crypto/Schnorr.d
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/EnrollmentPool.d
  source/agora/consensus/validation/Enrollment.d
  source/agora/node/Ledger.d
Labels: type-enhancement

#915 Refactoring the `EnrollmentManager`
  source/agora/consensus/EnrollmentManager.d
Labels: type-refactoring

#917 Enrollment validation: Use TestUTXOSet instead of UTXOSet
  source/agora/consensus/validation/Enrollment.d
Labels: type-refactoring

#916 Amount: Add support for division
  source/agora/common/Amount.d
Labels: type-enhancement

#922 Add a module with well-known test values
  source/agora/utils/Test.d
  source/scpd/quorum/QuorumIntersectionTests.d
  tests/unit/BlockStorage.d
Labels: type-feature

#924 Add a function to restart a given node (and a test for it)
  source/agora/test/Base.d
  source/agora/test/Simple.d
Labels: type-feature

#930 Slightly improve configuration parsing
  source/agora/common/Config.d
Labels: type-enhancement

#931 Don't throw on getMerklePath() failure
  source/agora/consensus/data/Block.d
  source/agora/node/Ledger.d
Labels: type-enhancement

#929 runNode: Move type from parameter to body
  source/agora/cli/multi/main.d
  source/agora/node/Runner.d
  source/agora/node/main.d
Labels: type-refactoring

#939 Remove Config.quorum in the `agora-multi`
  source/agora/cli/multi/main.d
Labels: type-bug

#947 The UTXOSet Refactoring and separated into UTXOSetValue and UTXOSet
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/EnrollmentPool.d
  source/agora/consensus/Quorum.d
  source/agora/consensus/UTXOSet.d
  source/agora/consensus/ValidatorSet.d
  source/agora/consensus/data/UTXOSetValue.d
  source/agora/consensus/validation/Block.d
  source/agora/consensus/validation/Enrollment.d
  source/agora/consensus/validation/Transaction.d
  source/agora/node/Ledger.d
  source/agora/test/Base.d
  source/agora/test/Ledger.d
Labels: type-refactoring

#933 Introduce a ManagedDatabase class
  source/agora/common/ManagedDatabase.d
  source/agora/common/TransactionPool.d
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/EnrollmentPool.d
  source/agora/consensus/UTXOSet.d
  source/agora/consensus/ValidatorSet.d
  source/agora/node/FullNode.d
  source/agora/node/Ledger.d
  source/agora/test/Base.d
Labels: type-enhancement, type-refactoring

#958 Serializer: Pass down `CompactMode` setting
  source/agora/common/Serializer.d
Labels: type-bug

#953 Use setTimer on Nominator.setupTimer
  source/agora/common/Task.d
  source/agora/consensus/protocol/Nominator.d
  source/agora/test/Base.d
Labels: type-enhancement

#960 Deserializer: Rise the default limit for length
  source/agora/common/Serializer.d
Labels: type-enhancement

#961 Ledger: Remove useless foreach in unittest
  source/agora/node/Ledger.d
Labels: type-refactoring

#964 Improve Ledger testability and reorder constructors arguments
  source/agora/node/FullNode.d
  source/agora/node/Ledger.d
Labels: type-refactoring

#967 Improve some unittests in Ledger
  source/agora/node/Ledger.d
Labels: type-refactoring

#966 MemBlockStorage: Detect when blocks failed to load
  source/agora/node/BlockStorage.d
Labels: type-bug

#968 Make Genesis keypair well-know, remove getGenesisKeyPair()
  source/agora/common/TransactionPool.d
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/EnrollmentPool.d
  source/agora/consensus/Genesis.d
  source/agora/consensus/ValidatorSet.d
  source/agora/consensus/validation/Block.d
  source/agora/node/BlockStorage.d
  source/agora/node/Ledger.d
  source/agora/test/BanManager.d
  source/agora/test/Base.d
  source/agora/test/EnrollmentManager.d
  source/agora/test/GenesisBlock.d
  source/agora/test/GossipProtocol.d
  source/agora/test/Ledger.d
  source/agora/test/NetworkClient.d
  source/agora/test/NetworkManager.d
  source/agora/test/Quorum.d
  source/agora/test/Simple.d
  source/agora/utils/Test.d
  tests/system/source/main.d
Labels: type-refactoring

#965 Implement a helper struct to build transactions
  source/agora/utils/Test.d
Labels: type-enhancement

#971 Add a copy constructor for Amount
  source/agora/common/Amount.d
Labels: type-enhancement

#976 Split well-known keypairs into their own module
  source/agora/utils/Test.d
  source/agora/utils/WellKnownKeys.d
Labels: type-refactoring

#938 Use atomic transactions when altering databases
  source/agora/common/ManagedDatabase.d
  source/agora/node/Ledger.d
Labels: type-feature

#977 Log failed request name & IP address
  source/agora/network/NetworkClient.d
Labels: type-refactoring

#980 Use fewer blocks in the quorum test
  source/agora/test/Quorum.d
Labels: type-refactoring

#986 Fix validation in setGenesisBlock()
  source/agora/consensus/Genesis.d
Labels: type-bug

#992 makeChainedTransactions: Remove the ability to change the genesis transaction
  source/agora/utils/Test.d
Labels: type-refactoring
