Repository bosagora/agora, pull requests merged in 2020-05, with the labels that each got.

#790 Remove unused quorum_conf from NetworkManager
  source/agora/network/NetworkManager.d
  source/agora/node/FullNode.d
  source/agora/test/Base.d
Labels: type-enhancement

#801 Move required peers into discovery() method
  source/agora/network/NetworkManager.d
  source/agora/node/FullNode.d
  source/agora/node/Validator.d
  source/agora/test/Base.d
Labels: type-refactoring

#802 Simplify createNewNode()
  source/agora/test/Base.d
  source/agora/test/NetworkManager.d
Labels: type-refactoring

#819 Print logs when constructor / start() fails
  source/agora/test/Base.d
Labels: type-enhancement

#828 Fix logging in catchup phase
  source/agora/network/NetworkManager.d
Labels: type-bug

#831 Test & fix BanManager's serialization
  source/agora/common/BanManager.d
Labels: type-bug

#826 Clear genesis enrollments properly
  source/agora/consensus/ValidatorSet.d
Labels: type-bug

#817 Sort enrollments in the call to makeNewBlock
  source/agora/consensus/data/Block.d
Labels: type-enhancement

#842 Fix 704: Split validation into a package
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/EnrollmentPool.d
  source/agora/consensus/ValidatorSet.d
  source/agora/consensus/validation/Block.d
  source/agora/consensus/validation/Enrollment.d
  source/agora/consensus/validation/PreImage.d
  source/agora/consensus/validation/Transaction.d
  source/agora/consensus/validation/package.d
  source/agora/node/Ledger.d
  source/agora/test/Ledger.d
Labels: type-refactoring

#840 Fix Enrollments not being loaded from the Genesis block
  source/agora/node/Ledger.d
Labels: type-bug

#777 Refactor TransactionPool a bit
  source/agora/common/TransactionPool.d
Labels: type-refactoring

#800 Add ability to create a merkle tree of arbitrary number of transactions
  source/agora/consensus/data/Block.d
Labels: type-enhancement

#851 Store the commitment as pre-image in the validator table
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/ValidatorSet.d
Labels: type-bug

#859 Run Serializer test first
  source/agora/test/Base.d
Labels: type-testing

#901 Simplify Block validation tests
  source/agora/consensus/validation/Block.d
Labels: type-enhancement
