Repository bosagora/agora, pull requests merged in 2020-07, with the labels that each got.

#994 Remove a redundant test in PrettyPrinter
  source/agora/utils/PrettyPrinter.d
Labels: type-testing

#997 Simplify some tests using `genesisSpendable()` and cleanup some imports
  source/agora/common/TransactionPool.d
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/EnrollmentPool.d
  source/agora/consensus/ValidatorSet.d
  source/agora/consensus/data/Block.d
  source/agora/consensus/data/Transaction.d
  source/agora/node/BlockStorage.d
  source/agora/test/ValidatorCount.d
  source/agora/utils/PrettyPrinter.d
Labels: type-refactoring

#996 Change ConsensusData to take an array of Transaction
  source/agora/consensus/data/ConsensusData.d
  source/agora/node/Ledger.d
  source/agora/utils/PrettyPrinter.d
  source/agora/utils/SCPPrettyPrinter.d
Labels: type-refactoring

#1001 Test: Use loops instead of copy-pasting code
  source/agora/consensus/EnrollmentPool.d
Labels: type-testing

#999 Remove test-only makeGenesisBlock utility
  source/agora/node/Ledger.d
Labels: type-testing

#1000 EnrollmentManager: Remove buggy call to setEnrollmentKey
  source/agora/consensus/EnrollmentManager.d
Labels: type-bug

#1002 Replace stateful makeEnrollment with stateless buildEnrollment
  source/agora/consensus/EnrollmentManager.d
  source/agora/node/Ledger.d
  source/agora/test/Base.d
Labels: type-enhancement, type-refactoring

#1003 Simplify another Ledger test to use loops instead of copy-paste
  source/agora/node/Ledger.d
Labels: type-refactoring

#1007 Fix #581: Remove or document usage of internal state in tests
  source/agora/test/Base.d
  source/agora/test/Metadata.d
Labels: type-testing

#1009 Emit unittested modules in the CI
  ci/run.sh
  source/agora/test/Base.d
Labels: type-testing

#1010 Take `NodeConfig.validator_cycle` into account
  source/agora/node/FullNode.d
  source/agora/node/Runner.d
  source/agora/node/Validator.d
  source/agora/node/main.d
  source/agora/test/Base.d
  source/agora/test/NetworkManager.d
Labels: type-bug

#1013 Fix makeEnrollment to generate different random seed
  source/agora/consensus/EnrollmentManager.d
Labels: type-bug

#1012 Tests: Make genBlocksToIndex accept a uint
  source/agora/node/Ledger.d
Labels: type-refactoring

#1014 Use TestLedger and ThrowingLedger more consistently in tests
  source/agora/node/Ledger.d
Labels: type-refactoring

#1016 Fix test Genesis seeds: Use ulong(0) instead of uint(0)
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/Genesis.d
Labels: type-testing

#1020 Fix race condition in the Ledger test
  source/agora/test/Ledger.d
Labels: type-bug

#1019 Don't process SCP messages if we're not enrolled
  source/agora/node/Validator.d
Labels: type-bug

#1017 Don't generate our own quorum twice
  source/agora/node/Validator.d
Labels: type-enhancement

#1022 Refactor some enrollment manager tests
  source/agora/consensus/EnrollmentManager.d
Labels: type-testing

#1023 Work around hashmap invalidation issue (+ small race condition fix)
  source/agora/network/NetworkManager.d
Labels: type-bug

#1026 Use proper Duration typing in the Config
  source/agora/common/Config.d
  source/agora/network/NetworkManager.d
  source/agora/test/BanManager.d
  source/agora/test/Base.d
  source/agora/test/NetworkClient.d
  source/agora/test/NetworkManager.d
Labels: type-refactoring

#1040 Bug fix: Avoid calling receivePreimage endlessly
  source/agora/consensus/validation/PreImage.d
  source/agora/test/EnrollmentManager.d
Labels: type-bug

#1045 Ledger tests: Simplify splitGenesisTransaction
  source/agora/node/Ledger.d
Labels: type-refactoring

#1050 SQlite: Use single quotes for string literals
  source/agora/consensus/EnrollmentManager.d
Labels: type-bug

#1053 sqlite: Don't use multiple handles to the same file
  source/agora/consensus/EnrollmentManager.d
  source/agora/consensus/EnrollmentPool.d
  source/agora/consensus/ValidatorSet.d
Labels: type-bug

#1005 Split the Genesis block in 3 modules
  source/agora/common/Serializer.d
  source/agora/consensus/data/Block.d
  source/agora/consensus/data/ConsensusData.d
  source/agora/consensus/data/genesis/Coinnet.d
  source/agora/consensus/data/genesis/Test.d
  source/agora/consensus/data/genesis/package.d
  source/agora/consensus/validation/Block.d
  source/agora/node/BlockStorage.d
  source/agora/node/FullNode.d
  source/agora/node/Ledger.d
  source/agora/test/BanManager.d
  source/agora/test/Base.d
  source/agora/test/EnrollmentManager.d
  source/agora/test/GenesisBlock.d
  source/agora/test/GossipProtocol.d
  source/agora/test/Ledger.d
  source/agora/test/NetworkClient.d
  source/agora/test/NetworkManager.d
  source/agora/test/Quorum.d
  source/agora/test/QuorumPreimage.d
  source/agora/test/Restart.d
  source/agora/test/Simple.d
  source/agora/utils/PrettyPrinter.d
  source/agora/utils/SCPPrettyPrinter.d
  source/agora/utils/Test.d
  tests/system/source/main.d
  tests/unit/BlockStorage.d
  tests/unit/BlockStorageChecksum.d
  tests/unit/BlockStorageMultiTx.d
Labels: type-refactoring
