Repository bosagora/agora, pull requests merged in 2020-09, with the labels that each got.

#1162 Demonstrate one bad and one potentially good signature scheme
  source/agora/common/crypto/ECC.d
  source/agora/common/crypto/Schnorr.d
Labels: type-enhancement

#1189 Ledger: Remove unused node_config field
  source/agora/node/FullNode.d
  source/agora/node/Ledger.d
Labels: type-refactoring

#1193 Remove Ledger.hasTransactionHash()
  source/agora/node/FullNode.d
  source/agora/node/Ledger.d
Labels: type-refactoring

#1212 Trivial: Organize `consensus/PreImage.d`
  source/agora/consensus/PreImage.d
Labels: type-refactoring

#1207 Emit hidden version of a secret key in log.trace
  source/agora/common/Types.d
  source/agora/common/crypto/ECC.d
  source/agora/common/crypto/Key.d
Labels: type-enhancement

#1223 Fix the integration tests to be able to run on OSX
  tests/system/dub.json
Labels: type-bug

#1204 Add LatestEnvelopes and store & restore envelopes
  dub.json
  source/agora/consensus/SCPEnvelopeStore.d
  source/agora/consensus/protocol/Nominator.d
  source/agora/node/Validator.d
  source/agora/test/Base.d
  source/agora/test/Byzantine.d
  source/agora/test/EnrollmentManager.d
  source/agora/test/MultiRoundConsensus.d
  source/agora/test/RestoreSCPState.d
Labels: type-enhancement
